[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"

# Decap CMS の admin ページに OAuth コールバックでアクセスする際のヘッダ
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
